name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
            toolchain: nightly
            override: true
            components: rustc
    
    - uses: actions/checkout@v3
    - name: Build
      run: cargo +nightly build --verbose
      
    - name: Run tests
      run: cargo +nightly test --verbose
    
    - name: Tarpaulin code coverage
      # You may pin to the exact commit or the version.
      # uses: actions-rs/tarpaulin@60f0b12e5beec09ccca51758913f82d01889151c
      uses: actions-rs/tarpaulin@v0.1.0
      with:
        # The version of cargo-tarpaulin to install
        version: latest
        # Extra command line arguments passed to cargo-tarpaulin
        args: '-- --force-clean --frozen --verbose'
        # The maximum time in seconds without a response from a test before timeout
        timeout: 60
        # The type of the coverage run [possible values: Tests, Doctests]
        run-types: Tests
